In [1]:
import pandas as pd
df=pd.read_csv('nse_all_stock_data.csv')
df.head()

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,...,COOLCAPS,ALLETEC,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
0,1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
l = {}

for i in df.columns:
    if i != 'Date':
        l[i]= df[i].mean() # mean of each column except Date column

In [3]:
# create a list of columns with null values >8000
null_cols = []
for i in df.columns:
    if df[i].isnull().sum() > 8000:
        null_cols.append(i)

print(null_cols)

['JIOFIN', 'ADANIENSOL', 'MANKIND', 'JSWINFRA', 'TATATECH', 'L&TFH', 'IREDA', 'MEDANTA', 'LLOYDSME', 'FIVESTAR', 'SIGNATURE', 'JYOTICNC', 'KAYNES', 'KPIL', 'RRKABEL', 'PPLPHARMA', 'NUVAMA', 'CELLO', 'NSLNISP', 'CONCORDBIO', 'HONASA', 'PVRINOX', 'ARE&M', 'BIKAJI', 'JUNIPER', 'INOXINDIA', 'KFINTECH', 'PTCIL', 'DOMS', 'REDTAPE', 'NETWEB', 'SBFC', 'HAPPYFORGE', 'SYRMA', 'ACI', 'AZAD', 'JLHL', 'TMB', 'EMIL', 'RUSTOMJEE', 'NIITMTS', 'TVSSCS', 'INDIASHLTR', 'BLUEJET', 'LTFOODS', 'SENCO', 'SANDUMA', 'UJJIVAN', 'CYIENTDLM', 'ASKAUTOLTD', 'LLOYDSENGG', 'HNDFDS', 'UTKARSHBNK', 'FUSION', 'SULA', 'SAMHI', 'KIRLPNU', 'EPIGRAL', 'GOPAL', 'SINDHUTRAD', 'ENTERO', 'JSFB', 'FEDFINA', 'PARKHOTELS', 'MAXESTATES', 'AARTIPHARM', 'HARSHA', 'YATHARTH', 'ZAGGLE', 'MEDIASSIST', 'INOXGREEN', 'MUTHOOTMF', 'GENSOL', 'DCXINDIA', 'AVALON', 'KALAMANDIR', 'LANDMARK', 'IDEAFORGE', 'SUNCLAY', 'BLSE', 'ESAFSFB', 'FLAIR', 'DREAMFOLKS', 'INNOVACAP', 'HMAAGRO', 'BAJEL', 'SPECTRUM', 'EXICOM', 'UNIPARTS', 'DIVGIITTS', 'YATRA', 'EMSLIMITED', 'NPST', 'IKIO', 'UDS', 'JSLL', 'RPTECH', 'MUFIN', 'SIGNPOST', 'GANDHAR', 'IRMENERGY', 'VPRPL', 'SCILAL', 'YASHO', 'PVSL', 'RISHABH', 'MOTISONS', 'CAPITALSFB', 'AEROFLEX', 'SADHNANIQ', 'SBGLP', 'EPACK', 'GPTHEALTH', 'ORIANA', 'RKSWAMY', 'AHL', 'ATL', 'GIRIRAJ', 'SKYGOLD', 'MVGJL', 'BETA', 'SAURASHCEM', 'SURAJEST', 'SICALLOG', 'TREL', 'PAKKA', 'INNOVANA', 'MUKKA', 'MUFTI', 'KRYSTAL', 'SPORTKING', 'KOTYARK', 'KAMOPAINTS', 'SYNCOMF', 'REMUS', 'BLAL', 'SATINDLTD', 'GSLSU', 'PLATIND', 'AMNPLST', 'NINSYS', 'OWAIS', 'TRACXN', 'FAZE3Q', 'BASILIC', 'ALPEXSOLAR', 'RADIANTCMS', 'DENTALKART', 'DBOL', 'DHARMAJ', 'VINYAS', 'TRU', 'GHCLTEXTIL', 'DAVANGERE', 'GRMOVER', 'SUKHJITS', 'EMKAYTOOLS', 'SAHANA', 'JGCHEM', 'ANNAPURNA', 'ELIN', 'SOLEX', 'VALIANTLAB', 'PHANTOMFX', 'KODYTECH', 'RBZJEWEL', 'ORIENTCER', 'KRISHIVAL', 'RATNAVEER', 'VISHNUINFR', 'VLEGOV', 'RACE', 'PYRAMID', 'ACCENTMIC', 'COOLCAPS', 'ALLETEC']

In [4]:
# create a new df with columns not in null_cols
df2 = df.drop(columns=null_cols)

# fill the remaining null values with the mean of the column not with date column
df2.fillna(l, inplace=True)
df2

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,...,MAZDA,MINDTECK,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
0,1991-01-02,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
1,1991-01-03,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
2,1991-01-04,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
3,1991-01-07,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
4,1991-01-08,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,2024-07-01,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,996.349976,429.049988,...,1434.300049,313.850006,220.410004,3.900000,402.799988,134.960007,384.850006,82.779999,211.089996,27.440001
8466,2024-07-02,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,985.450012,425.500000,...,1449.849976,305.649994,216.110001,3.870000,409.799988,130.729996,396.700012,83.349998,211.740005,27.770000
8467,2024-07-03,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,988.200012,428.299988,...,1432.449951,325.399994,227.800003,3.870000,429.350006,132.220001,394.200012,83.269997,225.880005,27.700001
8468,2024-07-04,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,1010.200012,429.049988,...,1422.050049,338.950012,227.429993,4.040000,428.750000,131.360001,388.250000,82.980003,223.800003,27.580000
8469,2024-07-05,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,1015.650024,433.649994,...,1420.750000,328.350006,224.720001,3.980000,421.350006,130.440002,388.799988,84.099998,241.740005,27.910000

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8470 entries, 0 to 8469
Columns: 1242 entries, Date to PRITIKAUTO
dtypes: float64(1241), object(1)
memory usage: 80.3+ MB

In [6]:
df2.describe()

,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,HINDUNILVR,...,MAZDA,MINDTECK,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
count,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,...,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000
mean,605.661551,1221.558660,437.622147,296.793689,359.974920,188.679499,429.695286,726.020834,133.909118,755.943850,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
std,687.533972,938.477755,486.047663,213.289896,193.966114,155.485714,430.230612,37.695587,111.558351,753.876716,...,146.195258,31.630378,23.512162,1.748618,113.017904,32.564955,50.613490,3.841359,27.603618,2.127224
min,10.975116,35.474998,2.435000,20.100000,9.350544,13.346102,0.763183,531.849976,4.182222,61.805000,...,233.699997,12.750000,7.100000,0.624703,14.000000,8.900000,51.150002,47.750000,59.349998,12.700000
25%,68.142830,527.012512,36.157499,171.468182,295.578590,43.955097,113.641209,726.020834,22.924722,207.762501,...,563.316218,92.740286,36.549999,4.378091,107.949997,31.400000,150.000000,71.400780,171.467658,20.554881
50%,443.062775,1221.558660,294.087509,296.793689,359.974920,188.679499,358.118744,726.020834,133.909118,455.875000,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
75%,605.661551,1236.475037,535.462479,296.793689,359.974920,253.587505,496.924988,726.020834,216.283337,851.274994,...,563.316218,92.740286,46.816379,4.378091,173.385619,49.874282,155.291620,71.400780,171.467658,20.554881
max,3177.250000,4219.250000,1768.650024,1233.400024,1475.800049,905.650024,1939.500000,1105.250000,492.149994,2812.449951,...,1556.550049,340.299988,227.800003,17.518017,806.200012,236.149994,660.000000,119.900002,332.000000,52.000000

In [7]:
#null Values
df2.isnull().sum()

Date          0
RELIANCE      0
TCS           0
HDFCBANK      0
ICICIBANK     0
             ..
DONEAR        0
CAREERP       0
INTLCONV      0
SHREEPUSHK    0
PRITIKAUTO    0
Length: 1242, dtype: int64

In [12]:
# count duplicate rows
df2.duplicated().sum()
df2.drop_duplicates(inplace=True)
df2.shape

(8470, 1242)

{'RELIANCE': 0, 'TCS': 0, 'HDFCBANK': 0, 'ICICIBANK': 0, 'BHARTIARTL': 0, 'SBIN': 0, 'INFY': 0, 'LICI': 0, 'ITC': 0, 'HINDUNILVR': 0, 'LT': 0, 'BAJFINANCE': 0, 'HCLTECH': 0, 'MARUTI': 0, 'SUNPHARMA': 0, 'ADANIENT': 0, 'KOTAKBANK': 0, 'TITAN': 0, 'ONGC': 0, 'TATAMOTORS': 0, 'NTPC': 0, 'AXISBANK': 0, 'DMART': 0, 'ADANIGREEN': 0, 'ADANIPORTS': 0, 'ULTRACEMCO': 0, 'ASIANPAINT': 0, 'COALINDIA': 0, 'BAJAJFINSV': 0, 'BAJAJ-AUTO': 0, 'POWERGRID': 0, 'NESTLEIND': 0, 'WIPRO': 0, 'M&M': 0, 'IOC': 0, 'HAL': 0, 'DLF': 0, 'ADANIPOWER': 0, 'JSWSTEEL': 0, 'TATASTEEL': 0, 'SIEMENS': 0, 'IRFC': 0, 'VBL': 0, 'ZOMATO': 0, 'PIDILITIND': 0, 'GRASIM': 0, 'SBILIFE': 0, 'BEL': 0, 'LTIM': 0, 'TRENT': 0, 'PNB': 0, 'INDIGO': 0, 'BANKBARODA': 0, 'HDFCLIFE': 0, 'ABB': 0, 'BPCL': 0, 'PFC': 0, 'GODREJCP': 0, 'TATAPOWER': 0, 'HINDALCO': 0, 'HINDZINC': 0, 'TECHM': 0, 'AMBUJACEM': 0, 'INDUSINDBK': 0, 'CIPLA': 0, 'GAIL': 0, 'RECLTD': 0, 'BRITANNIA': 0, 'UNIONBANK': 0, 'IOB': 0, 'LODHA': 0, 'EICHERMOT': 0, 'CANBK': 0, 'TATACONSUM': 0, 'DRREDDY': 0, 'TVSMOTOR': 0, 'ZYDUSLIFE': 0, 'ATGL': 0, 'VEDL': 0, 'CHOLAFIN': 0, 'HAVELLS': 0, 'HEROMOTOCO': 0, 'DABUR': 0, 'SHREECEM': 0, 'BAJAJHLDNG': 0, 'DIVISLAB': 0, 'APOLLOHOSP': 0, 'NHPC': 0, 'SHRIRAMFIN': 0, 'BOSCHLTD': 0, 'TORNTPHARM': 0, 'ICICIPRULI': 0, 'IDBI': 0, 'JSWENERGY': 0, 'JINDALSTEL': 0, 'BHEL': 0, 'INDHOTEL': 0, 'CUMMINSIND': 0, 'ICICIGI': 0, 'CGPOWER': 0, 'MCDOWELL-N': 0, 'HDFCAMC': 0, 'MAXHEALTH': 0, 'SOLARINDS': 0, 'MOTHERSON': 0, 'INDUSTOWER': 0, 'POLYCAB': 0, 'OFSS': 0, 'SRF': 0, 'IRCTC': 0, 'COLPAL': 0, 'LUPIN': 0, 'NAUKRI': 0, 'TIINDIA': 0, 'INDIANB': 0, 'HINDPETRO': 0, 'BERGEPAINT': 0, 'YESBANK': 0, 'TORNTPOWER': 0, 'OIL': 0, 'SBICARD': 0, 'IDEA': 0, 'MARICO': 0, 'GODREJPROP': 0, 'AUROPHARMA': 0, 'UCOBANK': 0, 'BANKINDIA': 0, 'PERSISTENT': 0, 'MUTHOOTFIN': 0, 'NMDC': 0, 'ALKEM': 0, 'PIIND': 0, 'LTTS': 0, 'GICRE': 0, 'TATACOMM': 0, 'JSL': 0, 'MRF': 0, 'SAIL': 0, 'PGHH': 0, 'SUZLON': 0, 'LINDEINDIA': 0, 'SUPREMEIND': 0, 'CONCOR': 0, 'OBEROIRLTY': 0, 'ASTRAL': 0, 'IDFCFIRSTB': 0, 'RVNL': 0, 'BHARATFORG': 0, 'CENTRALBK': 0, 'POLICYBZR': 0, 'ASHOKLEY': 0, 'THERMAX': 0, 'PHOENIXLTD': 0, 'GMRINFRA': 0, 'TATAELXSI': 0, 'PATANJALI': 0, 'SJVN': 0, 'PRESTIGE': 0, 'ACC': 0, 'NYKAA': 0, 'SUNDARMFIN': 0, 'UBL': 0, 'ABCAPITAL': 0, 'MPHASIS': 0, 'BALKRISIND': 0, 'DIXON': 0, 'MAHABANK': 0, 'KALYANKJIL': 0, 'SCHAEFFLER': 0, 'AWL': 0, 'APLAPOLLO': 0, 'SONACOMS': 0, 'KPITTECH': 0, 'FACT': 0, 'PSB': 0, 'PETRONET': 0, 'UNOMINDA': 0, 'PAGEIND': 0, 'MRPL': 0, 'AUBANK': 0, 'MAZDOCK': 0, 'HUDCO': 0, 'GUJGASLTD': 0, 'NIACL': 0, 'CRISIL': 0, 'AIAENG': 0, 'FEDERALBNK': 0, 'VOLTAS': 0, 'DALBHARAT': 0, 'POONAWALLA': 0, 'IRB': 0, '3MINDIA': 0, 'MFSL': 0, 'M&MFIN': 0, 'UPL': 0, 'HONAUT': 0, 'BSE': 0, 'FLUOROCHEM': 0, 'COFORGE': 0, 'LICHSGFIN': 0, 'GLAXO': 0, 'DELHIVERY': 0, 'BDL': 0, 'STARHEALTH': 0, 'FORTIS': 0, 'BIOCON': 0, 'COROMANDEL': 0, 'NLCINDIA': 0, 'TATAINVEST': 0, 'JKCEMENT': 0, 'IPCALAB': 0, 'METROBRAND': 0, 'KEI': 0, 'ESCORTS': 0, 'GLAND': 0, 'IGL': 0, 'NAM-INDIA': 0, 'APOLLOTYRE': 0, 'JUBLFOOD': 0, 'POWERINDIA': 0, 'MSUMI': 0, 'BANDHANBNK': 0, 'DEEPAKNTR': 0, 'ZFCVINDIA': 0, 'AJANTPHARM': 0, 'KPRMILL': 0, 'SYNGENE': 0, 'EIHOTEL': 0, 'APARINDS': 0, 'NATIONALUM': 0, 'TATACHEM': 0, 'GLENMARK': 0, 'HINDCOPPER': 0, 'GODREJIND': 0, 'NH': 0, 'BLUESTARCO': 0, 'EXIDEIND': 0, 'ENDURANCE': 0, 'JBCHEPHARM': 0, 'PAYTM': 0, 'ANGELONE': 0, 'MOTILALOFS': 0, 'ITI': 0, '360ONE': 0, 'CARBORUNIV': 0, 'AARTIIND': 0, 'SUNTV': 0, 'KIOCL': 0, 'ISEC': 0, 'RADICO': 0, 'SUNDRMFAST': 0, 'CREDITACC': 0, 'COCHINSHIP': 0, 'HATSUN': 0, 'MANYAVAR': 0, 'CYIENT': 0, 'GET&D': 0, 'BRIGADE': 0, 'TIMKEN': 0, 'NBCC': 0, 'JBMA': 0, 'GILLETTE': 0, 'KANSAINER': 0, 'LAURUSLABS': 0, 'GRINDWELL': 0, 'SWANENERGY': 0, 'CHOLAHLDNG': 0, 'IRCON': 0, 'SKFINDIA': 0, 'BSOFT': 0, 'ASTERDM': 0, 'RELAXO': 0, 'SONATSOFTW': 0, 'GSPL': 0, 'RATNAMANI': 0, 'ABFRL': 0, 'APLLTD': 0, 'PFIZER': 0, 'RAMCOCEM': 0, 'PEL': 0, 'ELGIEQUIP': 0, 'LALPATHLAB': 0, 'EMAMILTD': 0, 'SANOFI': 0, 'TRIDENT': 0, 'CASTROLIND': 0, 'KAJARIACER': 0, 'CENTURYTEX': 0, 'CHALET': 0, 'DEVYANI': 0, 'CDSL': 0, 'KEC': 0, 'SCHNEIDER': 0, 'IDFC': 0, 'BATAINDIA': 0, 'CIEINDIA': 0, 'SUMICHEM': 0, 'NATCOPHARM': 0, 'SUVENPHAR': 0, 'CROMPTON': 0, 'TRITURBINE': 0, 'INOXWIND': 0, 'ACE': 0, 'ATUL': 0, 'CGCL': 0, 'TVSHLTD': 0, 'SHYAMMETL': 0, 'KIMS': 0, 'PNBHOUSING': 0, 'REDINGTON': 0, 'LAXMIMACH': 0, 'JYOTHYLAB': 0, 'CESC': 0, 'GODFRYPHLP': 0, 'RITES': 0, 'INDIAMART': 0, 'AEGISCHEM': 0, 'OLECTRA': 0, 'WHIRLPOOL': 0, 'ANANDRATHI': 0, 'NAVINFLUOR': 0, 'JWL': 0, 'APTUS': 0, 'FINCABLES': 0, 'FINPIPE': 0, 'POLYMED': 0, 'VINATIORGA': 0, 'INTELLECT': 0, 'JAIBALAJI': 0, 'J&KBANK': 0, 'KARURVYSYA': 0, 'BLUEDART': 0, 'MANAPPURAM': 0, 'AFFLE': 0, 'NCC': 0, 'RBLBANK': 0, 'TTML': 0, 'BASF': 0, 'VGUARD': 0, 'CAMS': 0, 'GESHIP': 0, 'CENTURYPLY': 0, 'CLEAN': 0, 'JINDALSAW': 0, 'FSL': 0, 'ZENSARTECH': 0, 'SOBHA': 0, 'CHAMBLFERT': 0, 'DATAPATTNS': 0, 'CHENNPETRO': 0, 'WELCORP': 0, 'MGL': 0, 'KSB': 0, 'WELSPUNLIV': 0, 'HSCL': 0, 'DCMSHRIRAM': 0, 'ASTRAZEN': 0, 'ZEEL': 0, 'BEML': 0, 'HFCL': 0, 'RAINBOW': 0, 'ABSLAMC': 0, 'ASAHIINDIA': 0, 'IIFL': 0, 'BLS': 0, 'ALOKINDS': 0, 'VTL': 0, 'GRINFRA': 0, 'HBLPOWER': 0, 'WESTLIFE': 0, 'RKFORGE': 0, 'KIRLOSENG': 0, 'TITAGARH': 0, 'FINEORG': 0, 'AMBER': 0, 'SWSOLAR': 0, 'RAYMOND': 0, 'IEX': 0, 'SPARC': 0, 'GRAPHITE': 0, 'SPLPETRO': 0, 'RAILTEL': 0, 'INGERRAND': 0, 'ECLERX': 0, 'ERIS': 0, 'RHIM': 0, 'ENGINERSIN': 0, 'MAHSEAMLES': 0, 'HAPPSTMNDS': 0, 'JKTYRE': 0, 'TEJASNET': 0, 'PNCINFRA': 0, 'NEWGEN': 0, 'TANLA': 0, 'BIRLACORPN': 0, 'BBTC': 0, 'GMDCLTD': 0, 'NUVOCO': 0, 'AKZOINDIA': 0, 'CEATLTD': 0, 'RPOWER': 0, 'RELINFRA': 0, 'GPIL': 0, 'ELECON': 0, 'ANANTRAJ': 0, 'ELECTCAST': 0, 'DBREALTY': 0, 'EQUITASBNK': 0, 'BAJAJELEC': 0, 'LATENTVIEW': 0, 'JPPOWER': 0, 'GRANULES': 0, 'AAVAS': 0, 'AETHER': 0, 'UTIAMC': 0, 'LEMONTREE': 0, 'JKLAKSHMI': 0, 'GPPL': 0, 'SFL': 0, 'PCBL': 0, 'MAPMYINDIA': 0, 'ROUTE': 0, 'CANFINHOME': 0, 'CUB': 0, 'SAPPHIRE': 0, 'CAPLIPOINT': 0, 'MINDACORP': 0, 'MMTC': 0, 'IFCI': 0, 'PRAJIND': 0, 'VOLTAMP': 0, 'SCI': 0, 'USHAMART': 0, 'EIDPARRY': 0, 'RTNINDIA': 0, 'ANURAS': 0, 'GLS': 0, 'INFIBEAM': 0, 'FORCEMOT': 0, 'ZYDUSWELL': 0, 'STARCEMENT': 0, 'GODREJAGRO': 0, 'TTKPRESTIG': 0, 'ALKYLAMINE': 0, 'GNFC': 0, 'KPIGREEN': 0, 'CRAFTSMAN': 0, 'MAHLIFE': 0, 'JUBLPHARMA': 0, 'NETWORK18': 0, 'PRSMJOHNSN': 0, 'METROPOLIS': 0, 'CERA': 0, 'GRSE': 0, 'KIRLOSBROS': 0, 'UJJIVANSFB': 0, 'SHRIPISTON': 0, 'RENUKA': 0, 'RATEGAIN': 0, 'WOCKPHARMA': 0, 'SAFARI': 0, 'TECHNOE': 0, 'SHOPERSTOP': 0, 'IBULHSGFIN': 0, 'TEGA': 0, 'MEDPLUS': 0, 'MAHSCOOTER': 0, 'NEULANDLAB': 0, 'ESABINDIA': 0, 'GALAXYSURF': 0, 'ZENTEC': 0, 'JSWHL': 0, 'TV18BRDCST': 0, 'HOMEFIRST': 0, 'MHRIL': 0, 'POWERMECH': 0, 'KTKBANK': 0, 'MASTEK': 0, 'PGHL': 0, 'THOMASCOOK': 0, 'CCL': 0, 'GSFC': 0, 'RAJESHEXPO': 0, 'QUESS': 0, 'VARROC': 0, 'MANINFRA': 0, 'EASEMYTRIP': 0, 'VIPIND': 0, 'IONEXCHANG': 0, 'RESPONIND': 0, 'MIDHANI': 0, 'GAEL': 0, 'BALRAMCHIN': 0, 'STAR': 0, 'JUBLINGREA': 0, 'SARDAEN': 0, 'JMFINANCIL': 0, 'SOUTHBANK': 0, 'HEG': 0, 'CHEMPLASTS': 0, 'ARVIND': 0, 'RCF': 0, 'NAVA': 0, 'ALLCARGO': 0, 'ICIL': 0, 'IWEL': 0, 'KNRCON': 0, 'FDC': 0, 'RELIGARE': 0, 'GRAVITA': 0, 'MARKSANS': 0, 'AHLUCONT': 0, 'JUSTDIAL': 0, 'TRIVENI': 0, 'GARFIBRES': 0, 'VESUVIUS': 0, 'SAREGAMA': 0, 'DBL': 0, 'BALAMINES': 0, 'ISGEC': 0, 'AVANTIFEED': 0, 'INDIACEM': 0, 'BECTORFOOD': 0, 'CAMPUS': 0, 'VIJAYA': 0, 'GOCOLORS': 0, 'BORORENEW': 0, 'LXCHEM': 0, 'GREENLAM': 0, 'DEEPAKFERT': 0, 'CMSINFO': 0, 'KRBL': 0, 'ETHOSLTD': 0, 'TEXRAIL': 0, 'TCI': 0, 'IBREALEST': 0, 'JINDWORLD': 0, 'EMUDHRA': 0, 'PDSL': 0, 'GANESHHOUC': 0, 'CSBBANK': 0, 'SHAREINDIA': 0, 'IFBIND': 0, 'PRINCEPIPE': 0, 'VAIBHAVGBL': 0, 'ARVINDFASN': 0, 'EDELWEISS': 0, 'SPANDANA': 0, 'INDIGOPNTS': 0, 'GENUSPOWER': 0, 'SYMPHONY': 0, 'HGINFRA': 0, 'TIPSINDLTD': 0, 'SIS': 0, 'MSTCLTD': 0, 'NESCO': 0, 'SANGHVIMOV': 0, 'ITDCEM': 0, 'EPL': 0, 'SUPRAJIT': 0, 'SUNTECK': 0, 'HEMIPROP': 0, 'MOIL': 0, 'TIMETECHNO': 0, 'ASTRAMICRO': 0, 'TRIL': 0, 'WONDERLA': 0, 'GMMPFAUDLR': 0, 'SURYAROSNI': 0, 'VSTIND': 0, 'PTC': 0, 'JKPAPER': 0, 'SANSERA': 0, 'CHOICEIN': 0, 'AURIONPRO': 0, 'PAISALO': 0, 'ITDC': 0, 'PARADEEP': 0, 'KESORAMIND': 0, 'HCC': 0, 'ORCHPHARMA': 0, 'JAMNAAUTO': 0, 'ICRA': 0, 'RSYSTEMS': 0, 'PRUDENT': 0, 'MTARTECH': 0, 'RAIN': 0, 'DYNAMATECH': 0, 'JAICORPLTD': 0, 'RBA': 0, 'GATEWAY': 0, 'PURVA': 0, 'GUJALKALI': 0, 'NAZARA': 0, 'RALLIS': 0, 'VRLLOG': 0, 'GABRIEL': 0, 'DODLA': 0, 'JKIL': 0, 'ROLEXRINGS': 0, 'WABAG': 0, 'PRICOLLTD': 0, 'HCG': 0, 'AGI': 0, 'DBCORP': 0, 'DHANUKA': 0, 'MASFIN': 0, 'TDPOWERSYS': 0, 'GALLANTT': 0, 'JAYNECOIND': 0, 'GULFOILLUB': 0, 'TEAMLEASE': 0, 'TIIL': 0, 'JTEKTINDIA': 0, 'HEIDELBERG': 0, 'SUNDARMHLD': 0, 'RTNPOWER': 0, 'STLTECH': 0, 'JPASSOCIAT': 0, 'PATELENG': 0, 'ASHOKA': 0, 'PGEL': 0, 'NFL': 0, 'GOKEX': 0, 'BANCOINDIA': 0, 'VMART': 0, 'SHANTIGEAR': 0, 'GHCL': 0, 'SUDARSCHEM': 0, 'WELENT': 0, 'NOCIL': 0, 'TARC': 0, 'KKCL': 0, 'ORIENTELEC': 0, 'BOROLTD': 0, 'KIRLOSIND': 0, 'BALMLAWRIE': 0, 'FCL': 0, 'GRWRHITECH': 0, 'SHARDAMOTR': 0, 'TI': 0, 'AMIORG': 0, 'ORIENTCEM': 0, 'SHILPAMED': 0, 'AARTIDRUGS': 0, 'LGBBROSLTD': 0, 'TCIEXP': 0, 'WSTCSTPAPR': 0, 'ADVENZYMES': 0, 'PRIVISCL': 0, 'GREENPANEL': 0, 'VENUSPIPES': 0, 'BBOX': 0, 'IIFLSEC': 0, 'PILANIINVS': 0, 'ROSSARI': 0, 'KSL': 0, 'DCBBANK': 0, 'IMAGICAA': 0, 'BAJAJHIND': 0, 'DCAL': 0, 'BBL': 0, 'ORISSAMINE': 0, 'THANGAMAYL': 0, 'BHARATRAS': 0, 'KOLTEPATIL': 0, 'KSCL': 0, 'HATHWAY': 0, 'SSWL': 0, 'UNICHEMLAB': 0, 'CIGNITITEC': 0, 'IMFA': 0, 'ASHAPURMIN': 0, 'HGS': 0, 'SUBROS': 0, 'RAMKY': 0, 'SUNFLAG': 0, 'CARERATING': 0, 'SKIPPER': 0, 'LAOPALA': 0, 'LUMAXTECH': 0, 'BOMDYEING': 0, 'HIKAL': 0, 'JISLJALEQS': 0, 'CUPID': 0, 'LUXIND': 0, 'NUCLEUS': 0, 'TASTYBITE': 0, 'SOTL': 0, 'ARVSMART': 0, 'SANDHAR': 0, 'SALASAR': 0, 'NEOGEN': 0, 'DATAMATICS': 0, 'JTLIND': 0, 'ANUP': 0, 'HERITGFOOD': 0, 'THYROCARE': 0, 'VADILALIND': 0, 'NAVNETEDUL': 0, 'DISHTV': 0, 'KDDL': 0, 'INDOCO': 0, 'BAJAJCON': 0, 'TVSSRICHAK': 0, 'CARTRADE': 0, 'SBCL': 0, 'FIEMIND': 0, 'PRAKASH': 0, 'DELTACORP': 0, 'RAJRATAN': 0, 'MAHLOG': 0, 'PFOCUS': 0, 'GREAVESCOT': 0, 'DOLLAR': 0, 'UFLEX': 0, 'UNITECH': 0, 'BFUTILITIE': 0, 'SHARDACROP': 0, 'BANARISUG': 0, 'SEQUENT': 0, 'GREENPLY': 0, 'MAITHANALL': 0, 'SHK': 0, 'GUFICBIO': 0, 'DIACABS': 0, 'VSTTILLERS': 0, 'HLEGLAS': 0, 'BCG': 0, 'GOODLUCK': 0, 'SWARAJENG': 0, 'SEAMECLTD': 0, 'SMLISUZU': 0, 'ASHIANA': 0, 'DALMIASUG': 0, 'HINDWAREAP': 0, 'SAGCEM': 0, 'SAKSOFT': 0, 'APOLLO': 0, 'SUPRIYA': 0, 'AUTOAXLES': 0, 'STYLAMIND': 0, 'VINDHYATEL': 0, 'CARYSIL': 0, 'THEJO': 0, 'MPSLTD': 0, 'MARATHON': 0, 'ISMTLTD': 0, 'FILATEX': 0, 'NRBBEARING': 0, 'JCHAC': 0, 'MOLDTKPAC': 0, 'GMRP&UI': 0, 'SHALBY': 0, 'PFS': 0, 'AJMERA': 0, 'NILKAMAL': 0, 'RPGLIFE': 0, 'TATVA': 0, 'STYRENIX': 0, 'QUICKHEAL': 0, 'ACCELYA': 0, 'REPCOHOME': 0, 'PCJEWELLER': 0, 'APOLLOPIPE': 0, 'GANECOS': 0, 'PARAGMILK': 0, 'PSPPROJECT': 0, 'GIPCL': 0, 'XPROINDIA': 0, 'PITTIENG': 0, 'SHAKTIPUMP': 0, 'TIDEWATER': 0, 'SHAILY': 0, 'EVEREADY': 0, 'CONFIPET': 0, 'POLYPLEX': 0, 'TAJGVK': 0, 'TIRUMALCHM': 0, 'PARAS': 0, 'PGIL': 0, 'MANORAMA': 0, 'SOMANYCERA': 0, 'KINGFA': 0, 'FINOPB': 0, 'INDOSTAR': 0, 'HINDOILEXP': 0, 'SEPC': 0, 'INDIAGLYCO': 0, 'IPL': 0, 'GENESYS': 0, 'SANGHIIND': 0, 'BSHSL': 0, 'SATIN': 0, 'AXISCADES': 0, 'ARTEMISMED': 0, 'SASKEN': 0, 'EIHAHOTELS': 0, 'DHANI': 0, 'PRECWIRE': 0, 'VIDHIING': 0, 'APCOTEXIND': 0, 'HUHTAMAKI': 0, 'LUMAXIND': 0, 'GOCLCORP': 0, 'WENDT': 0, 'DEN': 0, 'HONDAPOWER': 0, 'KCP': 0, 'JAGRAN': 0, 'SANGAMIND': 0, 'BEPL': 0, 'CAPACITE': 0, 'SUVEN': 0, 'MANINDS': 0, 'DIAMONDYD': 0, 'CENTUM': 0, 'VENKEYS': 0, 'TCNSBRANDS': 0, 'OPTIEMUS': 0, 'MOREPENLAB': 0, 'MUKANDLTD': 0, 'ALEMBICLTD': 0, 'RAMASTEEL': 0, 'IOLCP': 0, 'MBAPL': 0, 'MMFL': 0, 'VAKRANGEE': 0, 'TARSONS': 0, 'ASTEC': 0, 'VISHNU': 0, 'TTKHLTCARE': 0, 'MTNL': 0, 'RPSGVENT': 0, 'ORIENTHOT': 0, 'GTLINFRA': 0, 'WEBELSOLAR': 0, 'JASH': 0, 'UGROCAP': 0, 'SDBL': 0, 'HPL': 0, 'TCPLPACK': 0, 'ADFFOODS': 0, 'HMT': 0, 'MOL': 0, 'THEMISMED': 0, 'PANAMAPET': 0, 'MANGLMCEM': 0, 'HITECH': 0, 'MAYURUNIQ': 0, 'SIYSIL': 0, 'JINDALPOLY': 0, 'KRSNAA': 0, 'DEEPINDS': 0, 'PNBGILTS': 0, 'HIL': 0, 'RICOAUTO': 0, 'BFINVEST': 0, 'IFGLEXPOR': 0, 'BARBEQUE': 0, 'ANDHRAPAP': 0, 'RIIL': 0, 'SHRIRAMPPS': 0, 'GLOBUSSPR': 0, 'DREDGECORP': 0, 'RUPA': 0, 'SJS': 0, 'PARACABLES': 0, 'EXPLEOSOL': 0, 'PRECAM': 0, 'BHARATWIRE': 0, 'GTPL': 0, 'ADORWELD': 0, 'DPABHUSHAN': 0, 'FOSECOIND': 0, 'SESHAPAPER': 0, 'JINDRILL': 0, 'GREENPOWER': 0, 'NITINSPIN': 0, 'GOLDIAM': 0, 'PIXTRANS': 0, 'SIGACHI': 0, 'ARMANFIN': 0, 'MONARCH': 0, 'AMRUTANJAN': 0, 'FMGOETZE': 0, 'PENIND': 0, 'GEPIL': 0, 'JUBLINDS': 0, '63MOONS': 0, 'CANTABIL': 0, 'RAMCOIND': 0, 'JYOTISTRUC': 0, 'VSSL': 0, 'HERCULES': 0, 'NSIL': 0, 'HLVLTD': 0, 'SURYODAY': 0, 'TNPL': 0, 'SUBEXLTD': 0, 'SERVOTECH': 0, 'BHAGCHEM': 0, 'ATFL': 0, 'OMAXE': 0, 'EVERESTIND': 0, 'PREMEXPLN': 0, 'GNA': 0, 'GOKULAGRO': 0, 'TALBROAUTO': 0, 'DCMSRIND': 0, 'NELCO': 0, 'KICL': 0, '5PAISA': 0, 'KIRIINDUS': 0, 'INDRAMEDCO': 0, 'SIRCA': 0, 'SHANKARA': 0, 'FAIRCHEMOR': 0, 'BLKASHYAP': 0, 'TFCILTD': 0, 'INDNIPPON': 0, 'GVKPIL': 0, 'RANEHOLDIN': 0, 'GEOJITFSL': 0, 'DCW': 0, 'BCLIND': 0, 'SMSPHARMA': 0, 'DPSCLTD': 0, 'CAMLINFINE': 0, 'CONTROLPR': 0, 'REFEX': 0, 'KRISHANA': 0, 'EKC': 0, 'WHEELS': 0, 'JITFINFRA': 0, 'V2RETAIL': 0, 'SALZERELEC': 0, 'UNIVCABLES': 0, 'SPAL': 0, 'SWELECTES': 0, 'HITECHGEAR': 0, 'INSECTICID': 0, 'PENINLAND': 0, 'SHREDIGCEM': 0, 'SPIC': 0, 'NIITLTD': 0, 'BIGBLOC': 0, 'SPCENET': 0, 'SHALPAINTS': 0, 'KAMDHENU': 0, 'STOVEKRAFT': 0, 'NAVKARCORP': 0, 'BUTTERFLY': 0, 'DHAMPURSUG': 0, 'NDTV': 0, 'ARIHANTSUP': 0, 'VASCONEQ': 0, 'KUANTUM': 0, 'APTECHT': 0, 'INDIANHUME': 0, 'ROSSELLIND': 0, 'SOLARA': 0, 'SUMMITSEC': 0, 'ALICON': 0, 'KSOLVES': 0, 'IGPL': 0, 'STEELCAS': 0, 'POKARNA': 0, 'ATULAUTO': 0, 'GANESHBE': 0, 'COSMOFIRST': 0, 'AWHCL': 0, 'DWARKESH': 0, 'HARIOMPIPE': 0, 'SMCGLOBAL': 0, 'MADRASFERT': 0, 'DSSL': 0, 'STEELXIND': 0, 'MONTECARLO': 0, 'E2E': 0, 'VERTOZ': 0, 'NGLFINE': 0, 'IGARASHI': 0, 'JAYBARMARU': 0, 'AVTNPL': 0, 'TVTODAY': 0, 'XCHANGING': 0, 'ANDHRSUGAR': 0, 'ACLGATI': 0, 'KOPRAN': 0, 'ENIL': 0, 'VERANDA': 0, 'OMINFRAL': 0, 'ZOTA': 0, 'SNOWMAN': 0, 'RAJRILTD': 0, 'PUNJABCHEM': 0, 'KITEX': 0, 'TEXINFRA': 0, 'IMPAL': 0, 'HIMATSEIDE': 0, 'DOLATALGO': 0, 'MANGCHEFER': 0, 'AGARIND': 0, 'REPRO': 0, 'DOLPHIN': 0, 'UTTAMSUGAR': 0, 'CENTRUM': 0, 'HESTERBIO': 0, 'MARINE': 0, 'BLISSGVS': 0, 'MSPL': 0, 'LINCOLN': 0, 'MATRIMONY': 0, 'HARDWYN': 0, 'GMBREW': 0, 'HERANBA': 0, 'RAMRAT': 0, 'DVL': 0, 'NACLIND': 0, 'RML': 0, 'NELCAST': 0, 'KOKUYOCMLN': 0, 'ALLSEC': 0, 'MACPOWER': 0, 'ROTO': 0, 'STERTOOLS': 0, 'TIL': 0, 'CSLFINANCE': 0, 'GICHSGFIN': 0, 'SATIA': 0, 'CREST': 0, 'AVADHSUGAR': 0, 'WINDLAS': 0, 'YUKEN': 0, 'ASIANENE': 0, 'CLSEL': 0, 'HUBTOWN': 0, 'VALIANTORG': 0, 'INDOTECH': 0, 'COFFEEDAY': 0, 'NDRAUTO': 0, 'DHANBANK': 0, 'ONEPOINT': 0, 'HIRECT': 0, 'KABRAEXTRU': 0, 'INDORAMA': 0, 'GULPOLY': 0, 'HEUBACHIND': 0, 'OAL': 0, 'CREATIVE': 0, 'ONWARDTEC': 0, 'URJA': 0, 'PVP': 0, 'ROHLTD': 0, 'VIMTALABS': 0, 'ZUARIIND': 0, 'NAHARSPING': 0, 'MANALIPETC': 0, 'SASTASUNDR': 0, 'DLINKINDIA': 0, 'RGL': 0, 'FOCUS': 0, 'GANDHITUBE': 0, 'KELLTONTEC': 0, 'KERNEX': 0, 'RAMCOSYS': 0, 'WALCHANNAG': 0, 'CHEMFAB': 0, 'UNIENTER': 0, 'SARVESHWAR': 0, 'BODALCHEM': 0, 'SEMAC': 0, 'VISAKAIND': 0, 'LIKHITHA': 0, 'WEL': 0, 'ASAL': 0, 'GPTINFRA': 0, 'SHIVALIK': 0, 'VHL': 0, 'EXCELINDUS': 0, 'INFOBEAN': 0, 'SANDESH': 0, 'EIMCOELECO': 0, 'CENTENKA': 0, 'HPAL': 0, 'MICEL': 0, 'ORIENTPPR': 0, 'MAXIND': 0, 'GRPLTD': 0, 'DENORA': 0, 'ASALCBR': 0, 'GKWLIMITED': 0, 'VLSFINANCE': 0, 'SPECIALITY': 0, 'CHEMCON': 0, 'SRHHYPOLTD': 0, 'PPL': 0, 'NCLIND': 0, 'HEXATRADEX': 0, 'DECCANCE': 0, 'SUTLEJTEX': 0, 'SPENCERS': 0, 'SILVERTUC': 0, 'SCHAND': 0, 'AGSTRA': 0, 'DYCL': 0, 'AMBIKCO': 0, 'BAJAJHCARE': 0, 'RSWM': 0, 'SAKAR': 0, 'MUNJALAU': 0, 'HMVL': 0, 'ELDEHSG': 0, 'INDOAMIN': 0, 'VIKASLIFE': 0, 'RUSHIL': 0, 'ADSL': 0, 'BCONCEPTS': 0, 'LINC': 0, 'RADHIKAJWE': 0, 'MAGADSUGAR': 0, 'CHEVIOT': 0, 'BALAJITELE': 0, 'OSWALGREEN': 0, 'ICEMAKE': 0, 'GFLLIMITED': 0, 'PANACEABIO': 0, 'STCINDIA': 0, 'UGARSUGAR': 0, 'MAANALU': 0, 'NRAIL': 0, 'JAGSNPHARM': 0, 'ASIANTILES': 0, 'POCL': 0, 'KOTHARIPET': 0, 'CONSOFINVT': 0, 'ACL': 0, 'ZUARI': 0, 'BEDMUTHA': 0, 'ESTER': 0, 'WSI': 0, 'TNPETRO': 0, 'FOODSIN': 0, 'THEINVEST': 0, 'DHUNINV': 0, 'TBZ': 0, 'KECL': 0, 'EMAMIPAP': 0, 'ELECTHERM': 0, 'LOKESHMACH': 0, 'SELAN': 0, 'AVG': 0, 'DMCC': 0, 'NECLIFE': 0, 'BIRLACABLE': 0, 'GOACARBON': 0, '3IINFOLTD': 0, 'WEALTH': 0, 'PARSVNATH': 0, 'ADVANIHOTR': 0, 'KRITI': 0, 'DPWIRES': 0, 'MEGASOFT': 0, 'OCCL': 0, 'MUNJALSHOW': 0, 'ZEEMEDIA': 0, 'MMP': 0, 'CHEMBOND': 0, 'JAYAGROGN': 0, 'JPOLYINVST': 0, 'MANAKSIA': 0, 'SREEL': 0, 'ONMOBILE': 0, 'SBC': 0, 'SPMLINFRA': 0, 'BHAGERIA': 0, 'MENONBE': 0, 'KILITCH': 0, 'PAVNAIND': 0, 'KHAICHEM': 0, 'FCSSOFT': 0, 'MALLCOM': 0, 'NRL': 0, 'APEX': 0, 'KAMATHOTEL': 0, 'HTMEDIA': 0, 'RUBYMILLS': 0, 'ALBERTDAVD': 0, 'LGHL': 0, 'PRIMESECU': 0, 'PLASTIBLEN': 0, 'IRISDOREME': 0, 'PDMJEPAPER': 0, 'INDSWFTLAB': 0, 'MIRZAINT': 0, 'STEL': 0, 'SAKUMA': 0, 'SIMPLEXINF': 0, 'ARROWGREEN': 0, 'VINYLINDIA': 0, 'OSWALAGRO': 0, 'HINDCOMPOS': 0, 'ARIHANTCAP': 0, 'MBLINFRA': 0, 'DEEPENR': 0, 'ORICONENT': 0, 'SHREYAS': 0, 'SKMEGGPROD': 0, 'DIGISPICE': 0, 'ZODIAC': 0, 'JETAIRWAYS': 0, 'JINDALPHOT': 0, 'RADIOCITY': 0, 'HCL-INSYS': 0, 'RBL': 0, 'KHADIM': 0, 'AXITA': 0, 'ASMS': 0, 'BIRLAMONEY': 0, 'BBTCL': 0, 'NAGAFERT': 0, 'GEECEE': 0, 'RITCO': 0, 'TCLCONS': 0, 'BALAXI': 0, 'REMSONSIND': 0, 'UFO': 0, 'PTL': 0, 'INDOBORAX': 0, 'MOLDTECH': 0, 'MAZDA': 0, 'MINDTECK': 0, '20MICRONS': 0, 'VIKASECO': 0, 'ORIENTBELL': 0, 'DONEAR': 0, 'CAREERP': 0, 'INTLCONV': 0, 'SHREEPUSHK': 0, 'PRITIKAUTO': 0}

KeyError: 'Open'

(8470, 1242)